// AUTO-GENERADO — no editar a mano. Generado por: node generate_seed.js
// Fuente: PostgreSQL crm_db.prospectos + expedientes
// Total: 52 prospectos de FERNANDA PALACIOS RIOS
// Fecha: 2026-05-20T07:58:41.216Z

export const DB_PROSPECTOS = [
  {
    "id": 2,
    "nombreCompleto": "Martha Patricia Huitron Arreola",
    "curp": "HUAM561213MDFTRR13",
    "nss": "01755623319",
    "telefonoContacto": "5573044181",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "m_martty@hotmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.068Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.068Z",
    "observaciones": "NOS ENVIO DOCUMENTOS, NOS FALTA EL VIDEO/ SEGUIMIENTO 11/05/2026/15/05/2026",
    "montoPensionActual": 4342.43,
    "aumentoPension": 10636.54,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021180064422323488",
    "nombreCarpetaDrive": "MARTHA PATRICIA HUITRON ARREOLA HUAM561213MDFTRR13 01755623319",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1LxpORf1stbvAQPSuoDOw2EojXZpyypWV",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 67848.44,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/1m__zlfsMO0ZMH3lPLSuXvC1IvRzsWZCs?usp=sharing",
    "comentarios": "NOS ENVIO DOCUMENTOS, NOS FALTA EL VIDEO/ SEGUIMIENTO 11/05/2026/15/05/2026"
  },
  {
    "id": 3,
    "nombreCompleto": "Leocadio Arroyo De La Torre",
    "curp": "AOTL610326HJCRRC07",
    "nss": "52846100320",
    "telefonoContacto": "3121216863",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.082Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.082Z",
    "observaciones": "NOS ENVIO MNJ   NOS CONTACTAREMOS CON EL NUEVAMENTE/SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 23717.52,
    "aumentoPension": null,
    "institucionBancaria": "SANTANDER MEXICANO",
    "cuentaClabe": "014098569246641254",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NOS ENVIO MNJ   NOS CONTACTAREMOS CON EL NUEVAMENTE/SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 4,
    "nombreCompleto": "Maria Avila Estrada",
    "curp": "AIEM630721MDFVSR04",
    "nss": "04866317557",
    "telefonoContacto": "6681290809",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.088Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.088Z",
    "observaciones": "ESTARA FUERA DE LA CIUDAD 2 SEMANAS AL REGRESAR ENVIARA LA DOCUMENTACIÁN",
    "montoPensionActual": 7920.51,
    "aumentoPension": null,
    "institucionBancaria": "INBURSA",
    "cuentaClabe": "036731500770264414",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ESTARA FUERA DE LA CIUDAD 2 SEMANAS AL REGRESAR ENVIARA LA DOCUMENTACIÁN"
  },
  {
    "id": 5,
    "nombreCompleto": "Gerardo Menendez Gagern",
    "curp": "MEGG631228HDFNGR01",
    "nss": "88806308735",
    "telefonoContacto": "7717091129",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "gerardo_mg28@yahoo.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.093Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.093Z",
    "observaciones": "DOCUMENTOS COMPLETOS",
    "montoPensionActual": 36525.14,
    "aumentoPension": 56876.45,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012313015208901778",
    "nombreCarpetaDrive": "GERARDO MENENDEZ GAGERN MEGG631228HDFNGR01 88806308735",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/19bUMVwPoDBsqw0qSe4vTMXWWKHBXuSgj",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 147848.44,
    "retroactivoFinal": 23500,
    "pagado": true,
    "linkConstancia": "https://drive.google.com/drive/folders/1PThpBInqmOGThwesmNYLFTWoltWfcBtf?usp=sharing",
    "comentarios": "DOCUMENTOS COMPLETOS"
  },
  {
    "id": 6,
    "nombreCompleto": "Jose De Jesus Tristan Ramirez",
    "curp": "TIRJ560531HSPRMS09",
    "nss": "43785619131",
    "telefonoContacto": "8135799543",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "jtristan667@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.098Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.098Z",
    "observaciones": "ENVIO DOCUMENTOS / EL LUNES ENVIA LA DOCUMENTACION",
    "montoPensionActual": 8257.98,
    "aumentoPension": 17199.14,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072580011409284582",
    "nombreCarpetaDrive": "JOSE DE JESUS TRISTAN RAMIREZ TIRJ560531HSPRMS09 43785619131",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1JvrYABlNsUWMucrADZbKZPSzrQli89DZ",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 81773.51,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIO DOCUMENTOS / EL LUNES ENVIA LA DOCUMENTACION"
  },
  {
    "id": 7,
    "nombreCompleto": "Rosa Icela Alegria Olvera",
    "curp": "AEOR680719MQTLLS05",
    "nss": "14846607712",
    "telefonoContacto": "",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.104Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.104Z",
    "observaciones": "SIN CEL PARA PODERLA CONTACTAR",
    "montoPensionActual": 4354.63,
    "aumentoPension": null,
    "institucionBancaria": "SANTANDER MEXICANO",
    "cuentaClabe": "014680569204648474",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SIN CEL PARA PODERLA CONTACTAR"
  },
  {
    "id": 8,
    "nombreCompleto": "Jose Guadalupe Alfredo Garcia Romero",
    "curp": "GARG621212HPLRMD01",
    "nss": "62826215204",
    "telefonoContacto": "2216636661",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "alfzep@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.110Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.110Z",
    "observaciones": "DOCUMENTOS COMPLETOS",
    "montoPensionActual": 9737.17,
    "aumentoPension": 19600.33,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012650015945590684",
    "nombreCarpetaDrive": "JOSE GUADALUPE ALFREDO GARCIA ROMERO GARG621212HPLRMD01 62826215204",
    "urlCarpetaDrive": "https://drive.google.com/drive/u/0/folders/1N52Er07dinIh_yI-K2ZVkR5ZtdiY6CFw",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 77848.44,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "DOCUMENTOS COMPLETOS"
  },
  {
    "id": 9,
    "nombreCompleto": "Pedro Muñiz Arriaga",
    "curp": "MUAP520702HSPXRD00",
    "nss": "43735216517",
    "telefonoContacto": "4443699104",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "pedroarriagamuniz@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.118Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.118Z",
    "observaciones": "FALTA DE DETALLE DE MOVIMIENTO , ESTADOS DE CUENTA Y VIDEO/ LO ESTA ASISTIENDO SU HIJA AUN NO LE BRINDAN EL DETALLE DE MOVIMIENTO",
    "montoPensionActual": 3869.36,
    "aumentoPension": 9665.62,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002700701046716735",
    "nombreCarpetaDrive": "PEDRO MUñIZ ARRIAGA MUAP520702HSPXRD00 43735216517",
    "urlCarpetaDrive": "https://drive.google.com/drive/u/0/folders/1Oabw3jmEP4DR7av8CI0WLYJZjQBaBnzR",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 47848.44,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "FALTA DE DETALLE DE MOVIMIENTO , ESTADOS DE CUENTA Y VIDEO/ LO ESTA ASISTIENDO SU HIJA AUN NO LE BRINDAN EL DETALLE DE MOVIMIENTO"
  },
  {
    "id": 10,
    "nombreCompleto": "Jose Alberto Hernandez Herrera",
    "curp": "HEHA570319HVZRRL08",
    "nss": "65775713947",
    "telefonoContacto": "2291392162",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.124Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.124Z",
    "observaciones": "LO ATENDIO GAEL/DUPLICADO/ Ricardo López grajales",
    "montoPensionActual": 4199.87,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002905904267794468",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "LO ATENDIO GAEL/DUPLICADO/ Ricardo López grajales"
  },
  {
    "id": 11,
    "nombreCompleto": "Guadalupe Avila Gil",
    "curp": "AIGG600822HSRVLD08",
    "nss": "24796024016",
    "telefonoContacto": "6861971098",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "avilagillupe@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.129Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.129Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 7503.03,
    "aumentoPension": 16809.14,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012028027704954845",
    "nombreCarpetaDrive": "GUADALUPE AVILA GIL AIGG600822HSRVLD08 24796024016",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1ryUiCYCsrxuSlCeC9gjyd31jBwV_7bXM",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 77143.81,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 12,
    "nombreCompleto": "Antonio Lopez Mendoza",
    "curp": "LOMA630501HSPPNN02",
    "nss": "43796350213",
    "telefonoContacto": "8123988006",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.134Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.134Z",
    "observaciones": "NO TUVIMOS RESPUESTA SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 5906.53,
    "aumentoPension": null,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072580008209900134",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NO TUVIMOS RESPUESTA SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 13,
    "nombreCompleto": "Reynaldo Isunza Ramirez",
    "curp": "IURR620207HCMSMY06",
    "nss": "52796206879",
    "telefonoContacto": "3123025482",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.139Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.139Z",
    "observaciones": "NO CONTETESTO LA LLAMADA SE LE ENVIO MNJ/SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 10171.24,
    "aumentoPension": null,
    "institucionBancaria": "BCO AZTECA",
    "cuentaClabe": "127094001804047173",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NO CONTETESTO LA LLAMADA SE LE ENVIO MNJ/SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 14,
    "nombreCompleto": "Benito Velazquez Hernandez",
    "curp": "VEHB560321HDFLRN06",
    "nss": "06765666554",
    "telefonoContacto": "5614108661",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "benito.vel@hotmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.144Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.144Z",
    "observaciones": "NOS ENVIARA DOCUMENTOS",
    "montoPensionActual": 5617.63,
    "aumentoPension": 12358.78,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002180904431307985",
    "nombreCarpetaDrive": "BENITO VELAZQUEZ HERNANDEZ VEHB560321HDFLRN06 06765666554",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1CCTtjAiCETgCevmjYRyXCk_lVaFmw6nQ",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 56535.47,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/1rWsP6LRBBzVl2Xyx4dbs_Mdbn8i2a5wM?usp=sharing",
    "comentarios": "NOS ENVIARA DOCUMENTOS"
  },
  {
    "id": 15,
    "nombreCompleto": "Ramon Filiberto De La Garza Salas",
    "curp": "GASR610822HNLRLM02",
    "nss": "43806126009",
    "telefonoContacto": "8181134389",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "reimondg22@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.149Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.149Z",
    "observaciones": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE",
    "montoPensionActual": 6262.86,
    "aumentoPension": 13935.61,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072580012597161558",
    "nombreCarpetaDrive": "RAMON FILIBERTO DE LA GARZA SALAS GASR610822HNLRLM02 43806126009",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/11uX-gMEU1fOTzVrpmH6q1YzJsy8f4ouX",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 56365.74,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE"
  },
  {
    "id": 16,
    "nombreCompleto": "Esteban Francisco Hernandez Gomez",
    "curp": "HEGE620118HCCRMS00",
    "nss": "81816200356",
    "telefonoContacto": "9845363477",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "ehg1962@hotmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.154Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.154Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 9298.03,
    "aumentoPension": 19600.33,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021920065408333525",
    "nombreCarpetaDrive": "ESTEBAN FRANCISCO HERNANDEZ GOMEZ HEGE620118HCCRMS00 81816200356",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/16h3L4N8OcBFKN3eyhL_HZ4Wc1uulvCIx",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 81773.51,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 17,
    "nombreCompleto": "Gilberto Trasviña Portillo",
    "curp": "TAPG621016HSLRRL08",
    "nss": "23816224564",
    "telefonoContacto": "6682437593",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.160Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.160Z",
    "observaciones": "NOS  ENVIARA  DOCUMENTACION/ LOS ENVIARA EL LUNES",
    "montoPensionActual": 18636.93,
    "aumentoPension": null,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072743012117929425",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NOS  ENVIARA  DOCUMENTACION/ LOS ENVIARA EL LUNES"
  },
  {
    "id": 18,
    "nombreCompleto": "Borja Enrique Leon Herrejon",
    "curp": "LEHB440715HMNNRR08",
    "nss": "53694412361",
    "telefonoContacto": "2224588497",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "15@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.165Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.165Z",
    "observaciones": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE/18/05/2026",
    "montoPensionActual": 16879.08,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012650015171189225",
    "nombreCarpetaDrive": "BORJA ENRIQUE LEON HERREJON LEHB440715HMNNRR08 53694412361",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1P5BqIsrpW_16G5DF9E931d7ctbw2liVp",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE/18/05/2026"
  },
  {
    "id": 19,
    "nombreCompleto": "Maximo Garcia Mucião",
    "curp": "GAMM500821HDFRCX06",
    "nss": "06735015809",
    "telefonoContacto": "5517969395",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.170Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.170Z",
    "observaciones": "TIENE MUCHAS DUDAS CON LO DEL % DE PAGO, REALIZO LLAMADA CERON SE LE CONTACTARA LA PROXIMA SEMANA/ SE LE AGENDO LLAMADA PARA EL 12 / DE MAYO A LAS 12 PM",
    "montoPensionActual": 3866.25,
    "aumentoPension": null,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021180063513783051",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "TIENE MUCHAS DUDAS CON LO DEL % DE PAGO, REALIZO LLAMADA CERON SE LE CONTACTARA LA PROXIMA SEMANA/ SE LE AGENDO LLAMADA PARA EL 12 / DE MAYO A LAS 12 PM"
  },
  {
    "id": 20,
    "nombreCompleto": "Remigio Hernandez Hernandez",
    "curp": "HEHR571209HVZRRM04",
    "nss": "67745703768",
    "telefonoContacto": "9212368425",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "hremigio679@mail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.175Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.175Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 4666.79,
    "aumentoPension": 10358.78,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015345142885",
    "nombreCarpetaDrive": "REMIGIO HERNANDEZ HERNANDEZ HEHR571209HVZRRM04 67745703768",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1BMinds9jIM3IbYBwyzl31i8djHTR7lZY",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 56535.47,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 21,
    "nombreCompleto": "Jose Gerardo Nuãez Garcia",
    "curp": "NUGG580117HDGXRR06",
    "nss": "32745739055",
    "telefonoContacto": "8715199636",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.180Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.180Z",
    "observaciones": "NOS ENVIARA DOCUMENTOS",
    "montoPensionActual": 8539.91,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012074015047342413",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NOS ENVIARA DOCUMENTOS"
  },
  {
    "id": 22,
    "nombreCompleto": "Juan Cruz Cruz",
    "curp": "CUCJ511022HMCRRN04",
    "nss": "16895100887",
    "telefonoContacto": "7152552762",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "juancruz7154@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.185Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.185Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 5617.63,
    "aumentoPension": 12213.05,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015263284304",
    "nombreCarpetaDrive": "JUAN CRUZ CRUZ CUCJ511022HMCRRN04 16895100887",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1SAAjqfPVbFctXkdO7ItC6lPl6OTmA-Bd",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 76313.04,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 23,
    "nombreCompleto": "Maria Elizabeth Sandoval Liera",
    "curp": "SALE620205MSLNRL00",
    "nss": "23846400523",
    "telefonoContacto": "6861903060",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.189Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.189Z",
    "observaciones": "PIEDE QUE SE LE REALICE LLAMADA NORMAL",
    "montoPensionActual": 7116.73,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012020015032902744",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "PIEDE QUE SE LE REALICE LLAMADA NORMAL"
  },
  {
    "id": 24,
    "nombreCompleto": "Jose Luis Ledesma Rocha",
    "curp": "LERL460806HDFDCS08",
    "nss": "11634622861",
    "telefonoContacto": "5535510267",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "joseluislesmarocha@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.194Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.194Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 3818.93,
    "aumentoPension": 9665.62,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002180902710155766",
    "nombreCarpetaDrive": "JOSE LUIS LEDESMA ROCHA LERL460806HDFDCS08 11634622861",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1D-v-lkqUhqo3TpM0qzkfmqs9Dnxr23BC",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 47848.44,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 25,
    "nombreCompleto": "Jose Maria Lopez Molina",
    "curp": "LOMM590524HSLPLR04",
    "nss": "23815904281",
    "telefonoContacto": "6674154572",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "Chemalopez709@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.199Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.199Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 4813.69,
    "aumentoPension": 10636.54,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015768603493",
    "nombreCarpetaDrive": "JOSE MARIA LOPEZ MOLINA LOMM590524HSLPLR04 23815904281",
    "urlCarpetaDrive": "https://drive.google.com/drive/u/0/folders/1f2y106kOqS6cclrmhQj3OqtI3mRs3tD_",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 61122.87,
    "retroactivoFinal": 26.06,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/1HDWXptxt7OHsyUmwcRnm7Kn0hvP3lGx7?usp=sharing",
    "comentarios": "COMPLETO"
  },
  {
    "id": 26,
    "nombreCompleto": "Jose Amado Vazquez",
    "curp": "AAVJ611212HDFMZS06",
    "nss": "10806149653",
    "telefonoContacto": "4922240307",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.204Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.204Z",
    "observaciones": "NO CONTESTO LA LLAMADA SE LE ENVIO MNJ/SEGUIMIENTO15/05/2026",
    "montoPensionActual": 7116.73,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "2.93491E+15",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NO CONTESTO LA LLAMADA SE LE ENVIO MNJ/SEGUIMIENTO15/05/2026"
  },
  {
    "id": 27,
    "nombreCompleto": "Sergio Martinez Avalos",
    "curp": "MAAS610213HCLRVR05",
    "nss": "32776102744",
    "telefonoContacto": "8666389303",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.209Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.209Z",
    "observaciones": "NO CONTESTO LA LLAMADA SE LE ENVIO MNJ",
    "montoPensionActual": 7116.73,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012580015803978065",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NO CONTESTO LA LLAMADA SE LE ENVIO MNJ"
  },
  {
    "id": 28,
    "nombreCompleto": "Fermin Manuel Resendiz Carrillo",
    "curp": "RECF620707HTSSRR00",
    "nss": "64846226260",
    "telefonoContacto": "8333088615",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "fermin.fmrc@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.215Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.215Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 7116.73,
    "aumentoPension": 16809.14,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021813065235134279",
    "nombreCarpetaDrive": "FERMIN MANUEL RESENDIZ CARRILLO RECF620707HTSSRR00 64846226260",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1WivqFxgC_3DXnsDcWYw6xTS9gI7rE_YD",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 77143.81,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/155nhgyA0DdaIJ131IV1vavV_ja_Mw9-I?usp=sharing",
    "comentarios": "COMPLETO"
  },
  {
    "id": 29,
    "nombreCompleto": "J. Jesus Gonzalez Gonzalez",
    "curp": "GOGJ611003HMCNNS04",
    "nss": "06796154950",
    "telefonoContacto": "5528051086",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "gonzalezjesus6044@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.220Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.220Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 17827.19,
    "aumentoPension": 32264.22,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015811307468",
    "nombreCarpetaDrive": "J. JESUS GONZALEZ GONZALEZ GOGJ611003HMCNNS04 06796154950",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1CVZAs5F1UIzuIabAN1Hc9kGcTsvIvXBa",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 81773.51,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "COMPLETO"
  },
  {
    "id": 30,
    "nombreCompleto": "Jose Guadalupe Chaboya Lopez",
    "curp": "CALG600325HTSHPD08",
    "nss": "49896005995",
    "telefonoContacto": "8671327437",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.225Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.225Z",
    "observaciones": "TELEFONO  DE UNA EMPRESA",
    "montoPensionActual": 5617.63,
    "aumentoPension": null,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072821011914296038",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "TELEFONO  DE UNA EMPRESA"
  },
  {
    "id": 31,
    "nombreCompleto": "Jose Angel Vazquez Beltran",
    "curp": "VABA551001HSPZLN04",
    "nss": "43735555914",
    "telefonoContacto": "4442033612",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "Angel Vazquez 5501@gmail . Com",
    "correoSipre": "peridaestradaangel@gmail.com",
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.231Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.231Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 7920.51,
    "aumentoPension": 16949.89,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072700008120649464",
    "nombreCarpetaDrive": "JOSE ANGEL VAZQUEZ BELTRAN VABA551001HSPZLN04 43735555914",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1xAvGg5OwDXrzoVo1NIPjqGU1kDjK8D6a",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 79403,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/1b1ktDn0-phLHK-H3N428HfxsrWw0hMYn?usp=sharing",
    "comentarios": "COMPLETO"
  },
  {
    "id": 32,
    "nombreCompleto": "Francisco Vazquez Rodriguez",
    "curp": "VARF641004HTSZDR01",
    "nss": "43826458812",
    "telefonoContacto": "8116664817",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.236Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.236Z",
    "observaciones": "NOS ENVIARA DOCUMENTOS",
    "montoPensionActual": 9081.52,
    "aumentoPension": null,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021580066242949776",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NOS ENVIARA DOCUMENTOS"
  },
  {
    "id": 33,
    "nombreCompleto": "Jesus Guerra Martinez",
    "curp": "GUMJ481009HTSRRS06",
    "nss": "49644816669",
    "telefonoContacto": "8332847725",
    "origenCanal": "Lote Fernanda",
    "estatus": "FORMALIZADO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "Impresossanjose@live.com.mx",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.242Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.242Z",
    "observaciones": "COMPLETO",
    "montoPensionActual": 3866.25,
    "aumentoPension": 10636.54,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002813901081684548",
    "nombreCarpetaDrive": "JESUS GUERRA MARTINEZ GUMJ481009HTSRRS06 49644816669",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1DkY-xErEvMVcdgbHSF17DWx7TJrK_cST",
    "estatusExpediente": "COMPLETO",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 66535.47,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": "https://drive.google.com/drive/folders/1CNXNS5oO_KSp3XX6uLiXouW-fPDJFUs2?usp=sharing",
    "comentarios": "COMPLETO"
  },
  {
    "id": 34,
    "nombreCompleto": "Maria Emma Martinez Yaãez",
    "curp": "MAYE630328MTSRXM04",
    "nss": "49926300648",
    "telefonoContacto": "8341214359",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.248Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.248Z",
    "observaciones": "SE LE ENVIO MNJ/ SEGUIMIENTO 15705/2026",
    "montoPensionActual": 9760.32,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012810015775757822",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE ENVIO MNJ/ SEGUIMIENTO 15705/2026"
  },
  {
    "id": 35,
    "nombreCompleto": "Rafael Rito Sandoval Garcia",
    "curp": "SAGR530522HMCNRF06",
    "nss": "16695115325",
    "telefonoContacto": "7224524634",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.253Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.253Z",
    "observaciones": "NOS CONTESTPO EL MNJ PERO LA LLAMADA AUN NO",
    "montoPensionActual": 3881.65,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012420029932672456",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "NOS CONTESTPO EL MNJ PERO LA LLAMADA AUN NO"
  },
  {
    "id": 36,
    "nombreCompleto": "Nicolas Garcia Lugo",
    "curp": "GALN530910HSRRGC06",
    "nss": "24735315871",
    "telefonoContacto": "6413271552",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "nicolasgarcialugo5@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.259Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.259Z",
    "observaciones": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE",
    "montoPensionActual": 4250.11,
    "aumentoPension": 10636.54,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072781010652643259",
    "nombreCarpetaDrive": "NICOLAS GARCIA LUGO GALN530910HSRRGC06 24735315871",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1KNlCO2sjC4Al4HmdYegVlWtIihkgVKBL",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 56535.47,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE"
  },
  {
    "id": 37,
    "nombreCompleto": "Maria Elena Gudião Ochoa",
    "curp": "GUOE590730MMNDCL07",
    "nss": "19745901017",
    "telefonoContacto": "5545494096",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.265Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.265Z",
    "observaciones": "ENVIARA DOCUMENTACION",
    "montoPensionActual": 4813.69,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015682661935",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA DOCUMENTACION"
  },
  {
    "id": 38,
    "nombreCompleto": "Anis Sarkis Mata",
    "curp": "SAMA510822HCLRTN02",
    "nss": "32925140108",
    "telefonoContacto": "8782660916",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.271Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.271Z",
    "observaciones": "SE LE ENVIO MNJ/SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 4636.43,
    "aumentoPension": null,
    "institucionBancaria": "SANTANDER MEXICANO",
    "cuentaClabe": "014075569086002908",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE ENVIO MNJ/SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 39,
    "nombreCompleto": "Sergio Saturnino Diaz Campuzano",
    "curp": "DICS631006HDGZMR09",
    "nss": "24846304350",
    "telefonoContacto": "6311988001",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "diazsaturnino1999@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.275Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.275Z",
    "observaciones": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE",
    "montoPensionActual": 9059.96,
    "aumentoPension": 19600.33,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072778013178243703",
    "nombreCarpetaDrive": "SERGIO SATURNINO DIAZ CAMPUZANO DICS631006HDGZMR09 24846304350",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1UQSe4PAtYmXVNSAXnOQpqhok3krCrxvL",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 81773.51,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "FALTA VIDEO ESTADOS DE CUENTA Y DETALLE"
  },
  {
    "id": 40,
    "nombreCompleto": "Patricia Castro Arista",
    "curp": "CAAP600312MHGSRT01",
    "nss": "21906016379",
    "telefonoContacto": "6643309165",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.281Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.281Z",
    "observaciones": "SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 6460.14,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002028904606670538",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 41,
    "nombreCompleto": "Ofelia Osornio Abrego",
    "curp": "OOAO500510MQTSBF06",
    "nss": "04665008027",
    "telefonoContacto": "3333595569",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.286Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.286Z",
    "observaciones": "ENVIARA LA DOCUMENTACION",
    "montoPensionActual": 3879.3,
    "aumentoPension": null,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072320002383454694",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA LA DOCUMENTACION"
  },
  {
    "id": 42,
    "nombreCompleto": "Luis Guzman Miron",
    "curp": "GUML500621HOCZRS01",
    "nss": "06705024146",
    "telefonoContacto": "5527047826",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.291Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.291Z",
    "observaciones": "ENVIARA LA DOCUMENTACION",
    "montoPensionActual": 9716.18,
    "aumentoPension": null,
    "institucionBancaria": "HSBC",
    "cuentaClabe": "021180064286539395",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA LA DOCUMENTACION"
  },
  {
    "id": 43,
    "nombreCompleto": "Enrique Soto",
    "curp": "SOXE540104HSLTXN00",
    "nss": "23735423826",
    "telefonoContacto": "6681505817",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.296Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.296Z",
    "observaciones": "SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026",
    "montoPensionActual": 5663,
    "aumentoPension": null,
    "institucionBancaria": "BANORTE",
    "cuentaClabe": "072731002704644180",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE ENVIO MNJ/ SEGUIMIENTO 15/05/2026"
  },
  {
    "id": 44,
    "nombreCompleto": "Margarito Poblano Plata",
    "curp": "POPM631017HPLBLR06",
    "nss": "62806310728",
    "telefonoContacto": "2441314377",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "poblanoplata@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.302Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.302Z",
    "observaciones": "LE BRINDARON UN CREDITO ENVIARA LA DOCUMENTACIÁN",
    "montoPensionActual": 7920.51,
    "aumentoPension": 16809.14,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012654015202312996",
    "nombreCarpetaDrive": "MARGARITO POBLANO PLATA POPM631017HPLBLR06 62806310728",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1xNiG5vxKzKXmcGNhVazZKBUoeBb0tfBv",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": 77143.81,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "LE BRINDARON UN CREDITO ENVIARA LA DOCUMENTACIÁN"
  },
  {
    "id": 45,
    "nombreCompleto": "Domingo Lopez Reyes",
    "curp": "LORD560414HVZPYM04",
    "nss": "67785603134",
    "telefonoContacto": "8187048783",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.307Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.307Z",
    "observaciones": "SE LE AGENDO LLAMADA A LAS 11 AM",
    "montoPensionActual": 8298.72,
    "aumentoPension": null,
    "institucionBancaria": "SANTANDER MEXICANO",
    "cuentaClabe": "014580605793187390",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE AGENDO LLAMADA A LAS 11 AM"
  },
  {
    "id": 46,
    "nombreCompleto": "Hipolito Solano Chavez",
    "curp": "SOCH550813HMNLHP07",
    "nss": "53745500552",
    "telefonoContacto": "7535336816",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.311Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.311Z",
    "observaciones": "ENVIO DOCUMENTOS",
    "montoPensionActual": 3882.85,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002497902686868427",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIO DOCUMENTOS"
  },
  {
    "id": 47,
    "nombreCompleto": "Jose Maria Carrasco Santiago",
    "curp": "CASM590318HCSRNR08",
    "nss": "67815952808",
    "telefonoContacto": "9211877061",
    "origenCanal": "Lote Fernanda",
    "estatus": "EN_PROCESO",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "chemacarrasco1959@gmail.com",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.317Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.317Z",
    "observaciones": "MECONTESTO SU HERMANA TERESA CARRASCO ELLA TAMBIEN ENVIO SUS DOCUMENTOS Y LOS ENVIARA EL DE LOS DOS",
    "montoPensionActual": 4813.69,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002854701532807363",
    "nombreCarpetaDrive": "JOSE MARIA CARRASCO SANTIAGO CASM590318HCSRNR08 67815952808",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/1veq5scGGYigrpnk-CMCpdDFU9SNgYyw3",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "MECONTESTO SU HERMANA TERESA CARRASCO ELLA TAMBIEN ENVIO SUS DOCUMENTOS Y LOS ENVIARA EL DE LOS DOS"
  },
  {
    "id": 48,
    "nombreCompleto": "Miguel Ortega Mendoza",
    "curp": "OEMM561124HCHRNG01",
    "nss": "33735615180",
    "telefonoContacto": "6141044319",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": false,
    "fechaIngreso": "2026-05-20T13:18:27.322Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.322Z",
    "observaciones": "SE LE ENVIO MNJ",
    "montoPensionActual": 3961.31,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "2.1509E+15",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "SE LE ENVIO MNJ"
  },
  {
    "id": 49,
    "nombreCompleto": "Tereza Carrasco Santiago",
    "curp": "CAST611003MCSRNR04",
    "nss": "67816279672",
    "telefonoContacto": "9212696029",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": "tetete1962@hotmail.com.mx",
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.327Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.327Z",
    "observaciones": "CONTESTO LA LLAMADA ES HERMANA DE LA CELDA 47 JESU CARMONA",
    "montoPensionActual": 4789.59,
    "aumentoPension": null,
    "institucionBancaria": null,
    "cuentaClabe": null,
    "nombreCarpetaDrive": "TEREZA CARRASCO SANTIAGO CAST611003MCSRNR04 67816279672",
    "urlCarpetaDrive": "https://drive.google.com/drive/folders/19NGn2xyd5hJPTN0B59BAwRrQhauQBa6S",
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "CONTESTO LA LLAMADA ES HERMANA DE LA CELDA 47 JESU CARMONA"
  },
  {
    "id": 50,
    "nombreCompleto": "Godinez Calette Roman",
    "curp": "GOCR570809HMCDLM08",
    "nss": "19755790920",
    "telefonoContacto": "5547918171",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.332Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.332Z",
    "observaciones": "$14,809.14  DE AUMENTO Y DE RETROACTIVO ( $53,863.64 )/ SOLICITA ASISTIR A LAS OFICINAS PARA REALIZAR EL TRAMITE",
    "montoPensionActual": 6370.38,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180015712538831",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "$14,809.14  DE AUMENTO Y DE RETROACTIVO ( $53,863.64 )/ SOLICITA ASISTIR A LAS OFICINAS PARA REALIZAR EL TRAMITE"
  },
  {
    "id": 51,
    "nombreCompleto": "Paz Zarza Javier",
    "curp": "PAZJ480719HDFZRV08",
    "nss": "01664878939",
    "telefonoContacto": "5533344262",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.337Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.337Z",
    "observaciones": "ENVIARA LA DOCUMENTACION",
    "montoPensionActual": 8963.27,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012180028415151609",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA LA DOCUMENTACION"
  },
  {
    "id": 52,
    "nombreCompleto": "Soledad Madrigal Maria De Jesus",
    "curp": "SOMJ660417MJCLDS02",
    "nss": "04886634163",
    "telefonoContacto": "3314333980",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.341Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.341Z",
    "observaciones": "ENVIARA LA DOCUMENTACION",
    "montoPensionActual": 8510.27,
    "aumentoPension": null,
    "institucionBancaria": "BBVA BANCOMER",
    "cuentaClabe": "012320015770724942",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA LA DOCUMENTACION"
  },
  {
    "id": 53,
    "nombreCompleto": "Zamora Lagunillas Jose Luis",
    "curp": "ZALL600705HTSMGS04",
    "nss": "43776046096",
    "telefonoContacto": "8186590145",
    "origenCanal": "Lote Fernanda",
    "estatus": "VIABLE",
    "curpValida": true,
    "nssValido": true,
    "correoElectronico": null,
    "correoSipre": null,
    "contactado": true,
    "fechaIngreso": "2026-05-20T13:18:27.346Z",
    "fechaUltimaActualizacion": "2026-05-20T13:18:27.346Z",
    "observaciones": "ENVIARA LA DOCUMENTACION",
    "montoPensionActual": 5617.63,
    "aumentoPension": null,
    "institucionBancaria": "BANAMEX",
    "cuentaClabe": "002010904400983976",
    "nombreCarpetaDrive": null,
    "urlCarpetaDrive": null,
    "estatusExpediente": "EN_RECOLECCION",
    "aprobacionSuperior": false,
    "aprobadoPor": null,
    "ineAmbosLados": "PENDIENTE",
    "comprobanteDomicilio": "PENDIENTE",
    "resolucionPension": "PENDIENTE",
    "estadosCuenta": "PENDIENTE",
    "fotoConIne": "PENDIENTE",
    "retroactivoFicticio": null,
    "retroactivoFinal": null,
    "pagado": false,
    "linkConstancia": null,
    "comentarios": "ENVIARA LA DOCUMENTACION"
  }
] as const;
